# Docker Compose 설정 파일
# version 속성은 더 이상 필요하지 않음 (Docker Compose v2)

services:
  broadcast:
    build: .
    container_name: broadcast-system
    image: broadcast-system:latest
    
    ports:
      - "8000:8000"    # 웹 서버 포트
    
    volumes:
      - ./data:/app/data              # 데이터 영속성
      - ./logs:/app/logs              # 로그 영속성
      - ./config:/app/config          # 설정 파일
    
    environment:
      - PYTHONUNBUFFERED=1
      - TARGET_IP=192.168.0.200       # 방송 서버 IP
      - TARGET_PORT=22000             # 방송 서버 포트
    
    # 오디오 장치 접근 (필요시)
    devices:
      - /dev/snd:/dev/snd             # 오디오 장치
    
    # 네트워크 설정
    # 옵션 1: bridge 네트워크 (권장 - 일반적인 경우)
    # 옵션 2: host 네트워크 (특수한 네트워크 요구사항이 있는 경우)
    # network_mode: "host"  # 이 줄의 주석을 제거하면 host 모드 사용
    
    restart: unless-stopped
    
    # 헬스체크
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 리소스 제한
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

